# Generated by Django 5.2 on 2025-04-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('1', 'Conserto'), ('2', 'Manutenção'), ('3', 'Instalação')])),
                ('value', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
