# Generated by Django 5.2 on 2025-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_category_alter_service_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Conserto', 'Conserto'), ('Manutenção', 'Manutenção'), ('Instalação', 'Instalação'), ('Consulta', 'Consulta')]),
        ),
    ]
