# Generated by Django 5.2 on 2025-04-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoitment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField()),
                ('name', models.CharField()),
                ('address', models.CharField(max_length=50)),
                ('address_number', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Visita em aberto', 'Visita em aberto'), ('A caminho', 'A caminho'), ('Situação pendente', 'Situação pendente'), ('Concluido', 'Concluido')], default='Visita em aberto', max_length=20)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
