# Generated by Django 5.2 on 2025-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='date',
            field=models.CharField(),
        ),
    ]
