# Generated by Django 5.2 on 2025-04-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='status',
            field=models.CharField(choices=[('1', 'Visita em aberto'), ('2', 'A caminho'), ('3', 'Situação pendente'), ('4', 'Concluido')], default='1', max_length=20),
        ),
    ]
