# Generated by Django 5.2 on 2025-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0002_appoitment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='status',
            field=models.CharField(choices=[('Visita em aberto', '1'), ('2', 'A caminho'), ('3', 'Situação pendente'), ('4', 'Concluido')], default='1', max_length=20),
        ),
    ]
