# Generated by Django 5.2 on 2025-04-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0003_alter_appoitment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='name',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
