# Generated by Django 5.2 on 2025-04-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0004_alter_appoitment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='hour',
            field=models.TimeField(),
        ),
    ]
