# Generated by Django 5.2 on 2025-04-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0005_alter_appoitment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='user',
            field=models.CharField(),
        ),
    ]
