# Generated by Django 5.2 on 2025-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0006_alter_appoitment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='hour',
            field=models.TimeField(),
        ),
    ]
