# Generated by Django 5.2 on 2025-04-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0006_alter_appoitment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
