# Generated by Django 5.2 on 2025-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitments', '0009_alter_appoitment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='status',
            field=models.CharField(choices=[('Visita em aberto', 'Visita em aberto'), ('A caminho', 'A caminho'), ('Situação pendente', 'Situação pendente'), ('Concluido', 'Concluido')], default='Visita em aberto', max_length=20),
        ),
    ]
