# Generated by Django 5.2 on 2025-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('1', 'Conserto'), ('2', 'Manutenção'), ('3', 'Instalação')])),
                ('value', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
