# Generated by Django 5.2 on 2025-04-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('1', 'Climatizador'), ('2', 'Cortina de Ar')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Appoitment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('address_number', models.IntegerField()),
                ('hour', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.service')),
            ],
        ),
    ]
