# Generated by Django 5.2 on 2025-04-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_product_alter_service_description_alter_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoitment',
            name='service',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Appoitment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
