# Generated by Django 5.2 on 2025-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Climatizador', 'Climatizador'), ('Cortina de Ar', 'Cortina de Ar'), ('Ar condicionado', 'Ar condicionado'), ('Filtro', 'Filtro'), ('Cabo', 'Cabo')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
